# Generated by Django 4.2.6 on 2023-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('personalId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'PersonalInformation',
                'ordering': ['date'],
            },
        ),
    ]
