# Generated by Django 4.2.5 on 2023-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_formdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(default=None, max_length=20, null=True, upload_to='images')),
            ],
            options={
                'db_table': 'ImageUpload',
                'get_latest_by': 'datetime',
            },
        ),
    ]
