# to create the docker image and run the container and the django project too 
FROM python:3

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /djangoapp

COPY . .

# install dependencies
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000

# run django 
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

