# Generated by Django 4.2.5 on 2023-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=None, max_length=50, null=True, upload_to='files'),
        ),
    ]
