# Generated by Django 4.2.5 on 2023-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
