# Generated by Django 4.2.6 on 2023-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField(unique=True)),
                ('author', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'db_table': 'QuotesCollection',
                'ordering': ['author'],
            },
        ),
    ]
