# Generated by Django 4.2.6 on 2023-10-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotescollection',
            table='QuotesCollectionsss',
        ),
    ]
